package com.src.entities;

import java.util.Date;

// Generated Apr 21, 2016 3:13:00 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * MatchsummaryId generated by hbm2java
 */
public class MatchSummary{

	private String matchid;
	private String player1;
	private String player2;
	private Integer rank1;
	private Integer rank2;
	private String player1Id;
	private String player2Id;
	private String oddPlayer1;
	private String oddPlayer2;
	private Integer won;
	private Integer countOfSets;
	private Integer countOfSetsInGame;
	private Integer set1;
	private Integer set2;
	private Integer set3;
	private String winnerName;
	private String betterRankPlayer;
	private String matchdate;
	private Date originaldate;
	
	public String toString() {
		return "MatchSummary [matchid=" + matchid + ", player1=" + player1
				+ ", player2=" + player2 + ", rank1=" + rank1 + ", rank2="
				+ rank2 + ", player1Id=" + player1Id + ", player2Id="
				+ player2Id + ", oddPlayer1=" + oddPlayer1 + ", oddPlayer2="
				+ oddPlayer2 + ", won=" + won + ", countOfSets=" + countOfSets
				+ ", countOfSetsInGame=" + countOfSetsInGame + ", set1=" + set1
				+ ", set2=" + set2 + ", set3=" + set3 + ", set4=" + set4
				+ ", set5=" + set5 + "]";
	}

	private Integer set4;
	private Integer set5;

	public MatchSummary() {
	}

	public MatchSummary(String matchid) {
		this.matchid = matchid;
	}

	public MatchSummary(String matchid, String player1, String player2, Integer rank1, Integer rank2,
			String player1Id, String player2Id, String oddPlayer1, String oddPlayer2, Integer won, Integer countOfSets,
			Integer countOfSetsInGame, Integer set1, Integer set2, Integer set3, Integer set4, Integer set5) {
		this.matchid = matchid;
		this.player1 = player1;
		this.player2 = player2;
		this.rank1 = rank1;
		this.rank2 = rank2;
		this.player1Id = player1Id;
		this.player2Id = player2Id;
		this.oddPlayer1 = oddPlayer1;
		this.oddPlayer2 = oddPlayer2;
		this.won = won;
		this.countOfSets = countOfSets;
		this.countOfSetsInGame = countOfSetsInGame;
		this.set1 = set1;
		this.set2 = set2;
		this.set3 = set3;
		this.set4 = set4;
		this.set5 = set5;
	}

	public String getMatchid() {
		return this.matchid;
	}

	public void setMatchid(String matchid) {
		this.matchid = matchid;
	}

	public String getPlayer1() {
		return this.player1;
	}

	public void setPlayer1(String player1) {
		this.player1 = player1;
	}

	public String getPlayer2() {
		return this.player2;
	}

	public void setPlayer2(String player2) {
		this.player2 = player2;
	}

	public Integer getRank1() {
		return this.rank1;
	}

	public void setRank1(Integer rank1) {
		this.rank1 = rank1;
	}

	public Integer getRank2() {
		return this.rank2;
	}

	public void setRank2(Integer rank2) {
		this.rank2 = rank2;
	}

	public String getPlayer1Id() {
		return this.player1Id;
	}

	public void setPlayer1Id(String player1Id) {
		this.player1Id = player1Id;
	}

	public String getPlayer2Id() {
		return this.player2Id;
	}

	public void setPlayer2Id(String player2Id) {
		this.player2Id = player2Id;
	}

	public String getOddPlayer1() {
		return this.oddPlayer1;
	}

	public void setOddPlayer1(String oddPlayer1) {
		this.oddPlayer1 = oddPlayer1;
	}

	public String getOddPlayer2() {
		return this.oddPlayer2;
	}

	public void setOddPlayer2(String oddPlayer2) {
		this.oddPlayer2 = oddPlayer2;
	}

	public Integer getWon() {
		return this.won;
	}

	public void setWon(Integer won) {
		this.won = won;
	}

	public Integer getCountOfSets() {
		return this.countOfSets;
	}

	public void setCountOfSets(Integer countOfSets) {
		this.countOfSets = countOfSets;
	}

	public Integer getCountOfSetsInGame() {
		return this.countOfSetsInGame;
	}

	public void setCountOfSetsInGame(Integer countOfSetsInGame) {
		this.countOfSetsInGame = countOfSetsInGame;
	}

	public Integer getSet1() {
		return this.set1;
	}

	public void setSet1(Integer set1) {
		this.set1 = set1;
	}

	public Integer getSet2() {
		return this.set2;
	}

	public void setSet2(Integer set2) {
		this.set2 = set2;
	}

	public Integer getSet3() {
		return this.set3;
	}

	public void setSet3(Integer set3) {
		this.set3 = set3;
	}

	public Integer getSet4() {
		return this.set4;
	}

	public void setSet4(Integer set4) {
		this.set4 = set4;
	}

	public Integer getSet5() {
		return this.set5;
	}

	public void setSet5(Integer set5) {
		this.set5 = set5;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatchSummary))
			return false;
		MatchSummary castOther = (MatchSummary) other;

		return ((this.getMatchid() == castOther.getMatchid()) || (this.getMatchid() != null
				&& castOther.getMatchid() != null && this.getMatchid().equals(castOther.getMatchid())))
				&& ((this.getPlayer1() == castOther.getPlayer1()) || (this.getPlayer1() != null
						&& castOther.getPlayer1() != null && this.getPlayer1().equals(castOther.getPlayer1())))
				&& ((this.getPlayer2() == castOther.getPlayer2()) || (this.getPlayer2() != null
						&& castOther.getPlayer2() != null && this.getPlayer2().equals(castOther.getPlayer2())))
				&& ((this.getRank1() == castOther.getRank1()) || (this.getRank1() != null
						&& castOther.getRank1() != null && this.getRank1().equals(castOther.getRank1())))
				&& ((this.getRank2() == castOther.getRank2()) || (this.getRank2() != null
						&& castOther.getRank2() != null && this.getRank2().equals(castOther.getRank2())))
				&& ((this.getPlayer1Id() == castOther.getPlayer1Id()) || (this.getPlayer1Id() != null
						&& castOther.getPlayer1Id() != null && this.getPlayer1Id().equals(castOther.getPlayer1Id())))
				&& ((this.getPlayer2Id() == castOther.getPlayer2Id()) || (this.getPlayer2Id() != null
						&& castOther.getPlayer2Id() != null && this.getPlayer2Id().equals(castOther.getPlayer2Id())))
				&& ((this.getOddPlayer1() == castOther.getOddPlayer1()) || (this.getOddPlayer1() != null
						&& castOther.getOddPlayer1() != null && this.getOddPlayer1().equals(castOther.getOddPlayer1())))
				&& ((this.getOddPlayer2() == castOther.getOddPlayer2()) || (this.getOddPlayer2() != null
						&& castOther.getOddPlayer2() != null && this.getOddPlayer2().equals(castOther.getOddPlayer2())))
				&& ((this.getWon() == castOther.getWon()) || (this.getWon() != null && castOther.getWon() != null
						&& this.getWon().equals(castOther.getWon())))
				&& ((this.getCountOfSets() == castOther.getCountOfSets())
						|| (this.getCountOfSets() != null && castOther.getCountOfSets() != null
								&& this.getCountOfSets().equals(castOther.getCountOfSets())))
				&& ((this.getCountOfSetsInGame() == castOther.getCountOfSetsInGame())
						|| (this.getCountOfSetsInGame() != null && castOther.getCountOfSetsInGame() != null
								&& this.getCountOfSetsInGame().equals(castOther.getCountOfSetsInGame())))
				&& ((this.getSet1() == castOther.getSet1()) || (this.getSet1() != null && castOther.getSet1() != null
						&& this.getSet1().equals(castOther.getSet1())))
				&& ((this.getSet2() == castOther.getSet2()) || (this.getSet2() != null && castOther.getSet2() != null
						&& this.getSet2().equals(castOther.getSet2())))
				&& ((this.getSet3() == castOther.getSet3()) || (this.getSet3() != null && castOther.getSet3() != null
						&& this.getSet3().equals(castOther.getSet3())))
				&& ((this.getSet4() == castOther.getSet4()) || (this.getSet4() != null && castOther.getSet4() != null
						&& this.getSet4().equals(castOther.getSet4())))
				&& ((this.getSet5() == castOther.getSet5()) || (this.getSet5() != null && castOther.getSet5() != null
						&& this.getSet5().equals(castOther.getSet5())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMatchid() == null ? 0 : this.getMatchid().hashCode());
		result = 37 * result + (getPlayer1() == null ? 0 : this.getPlayer1().hashCode());
		result = 37 * result + (getPlayer2() == null ? 0 : this.getPlayer2().hashCode());
		result = 37 * result + (getRank1() == null ? 0 : this.getRank1().hashCode());
		result = 37 * result + (getRank2() == null ? 0 : this.getRank2().hashCode());
		result = 37 * result + (getPlayer1Id() == null ? 0 : this.getPlayer1Id().hashCode());
		result = 37 * result + (getPlayer2Id() == null ? 0 : this.getPlayer2Id().hashCode());
		result = 37 * result + (getOddPlayer1() == null ? 0 : this.getOddPlayer1().hashCode());
		result = 37 * result + (getOddPlayer2() == null ? 0 : this.getOddPlayer2().hashCode());
		result = 37 * result + (getWon() == null ? 0 : this.getWon().hashCode());
		result = 37 * result + (getCountOfSets() == null ? 0 : this.getCountOfSets().hashCode());
		result = 37 * result + (getCountOfSetsInGame() == null ? 0 : this.getCountOfSetsInGame().hashCode());
		result = 37 * result + (getSet1() == null ? 0 : this.getSet1().hashCode());
		result = 37 * result + (getSet2() == null ? 0 : this.getSet2().hashCode());
		result = 37 * result + (getSet3() == null ? 0 : this.getSet3().hashCode());
		result = 37 * result + (getSet4() == null ? 0 : this.getSet4().hashCode());
		result = 37 * result + (getSet5() == null ? 0 : this.getSet5().hashCode());
		return result;
	}
		public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

		public String getWinnerName() {
		return winnerName;
	}

	public void setWinnerName(String winnerName) {
		this.winnerName = winnerName;
	}

		public String getBetterRankPlayer() {
		return betterRankPlayer;
	}

	public void setBetterRankPlayer(String betterRankPlayer) {
		this.betterRankPlayer = betterRankPlayer;
	}

		public String getMatchdate() {
		return matchdate;
	}

	public void setMatchdate(String matchdate) {
		this.matchdate = matchdate;
	}

		public Date getOriginaldate() {
		return originaldate;
	}

	public void setOriginaldate(Date originaldate) {
		this.originaldate = originaldate;
	}

		private String gender;


}
